namespace CSMSAdmin {
	public class Constants {
		public static string[] permissionStateAbbrs = {
			"D",
			"R",
			"G",
			"W",
		};

		public static string[] permissionStates = {
			"Deny",
			"Revoke",
			"Grant",
			"Grant with Grant Option"
		};

		public static string[] serverPermissionTypeAbbr = {
			"DBO",
			"AL",
			"ALCD",
			"ALCO",
			"ALDB",
			"ALES",
			"ALHE",
			"ALLG",
			"ALLS",
			"ALRS",
			"ALSS",
			"ALST",
			"ALTR",
			"AUTH",
			"CL",
			"CO",
			"COSQ",
			"CRDB",
			"CRDE",
			"CRHE",
			"CRTE",
			"IM",
			"SHDN",
			"TO",
			"VW",
			"VWAD",
			"VWDB",
			"VWSS",
			"XA"
		};

		public static string[] serverPermissionType = {
			"ADMINISTER BULK OPERATIONS",
			"ALTER",
			"ALTER ANY CREDENTIAL",
			"ALTER ANY CONNECTION",
			"ALTER ANY DATABASE",
			"ALTER ANY EVENT NOTIFICATION",
			"ALTER ANY ENDPOINT",
			"ALTER ANY LOGIN",
			"ALTER ANY LINKED SERVER",
			"ALTER RESOURCES",
			"ALTER SERVER STATE",
			"ALTER SETTINGS",
			"ALTER TRACE",
			"AUTHENTICATE SERVER",
			"CONTROL",
			"CONNECT",
			"CONNECT SQL",
			"CREATE ANY DATABASE",
			"CREATE DDL EVENT NOTIFICATION",
			"CREATE ENDPOINT",
			"CREATE TRACE EVENT NOTIFICATION",
			"IMPERSONATE",
			"SHUTDOWN",
			"TAKE OWNERSHIP",
			"VIEW DEFINITION",
			"VIEW ANY DEFINITION",
			"VIEW ANY DATABASE",
			"VIEW SERVER STATE",
			"EXTERNAL ACCESS"
		};

		public static string[] databasePermissionTypeAbbr = {
			"AL",
			"ALAK",
			"ALAR",
			"ALAS",
			"ALCF",
			"ALDS",
			"ALED",
			"ALFT",
			"ALMT",
			"ALRL",
			"ALRT",
			"ALSB",
			"ALSC",
			"ALSK",
			"ALSM",
			"ALSV",
			"ALTG",
			"ALUS",
			"AUTH",
			"BADB",
			"BALO",
			"CL",
			"CO",
			"CORP",
			"CP",
			"CRAG",
			"CRAK",
			"CRAS",
			"CRCF",
			"CRDB",
			"CRDF",
			"CRED",
			"CRFN",
			"CRFT",
			"CRMT",
			"CRPR",
			"CRQU",
			"CRRL",
			"CRRT",
			"CRRU",
			"CRSB",
			"CRSC",
			"CRSK",
			"CRSM",
			"CRSN",
			"CRSV",
			"CRTB",
			"CRTY",
			"CRVW",
			"CRXS",
			"DL",
			"EX",
			"IM",
			"IN",
			"RC",
			"RF",
			"SL",
			"SN",
			"SPLN",
			"SUQN",
			"TO",
			"UP",
			"VW",
			"VWCT",
			"VWDS"
		};

		public static string[] databasePermissionType = {
			"ALTER",
			"ALTER ANY ASYMMETRIC KEY",
			"ALTER ANY APPLICATION ROLE",
			"ALTER ANY ASSEMBLY",
			"ALTER ANY CERTIFICATE",
			"ALTER ANY DATASPACE",
			"ALTER ANY DATABASE EVENT NOTIFICATION",
			"ALTER ANY FULLTEXT CATALOG",
			"ALTER ANY MESSAGE TYPE",
			"ALTER ANY ROLE",
			"ALTER ANY ROUTE",
			"ALTER ANY REMOTE SERVICE BINDING",
			"ALTER ANY CONTRACT",
			"ALTER ANY SYMMETRIC KEY",
			"ALTER ANY SCHEMA",
			"ALTER ANY SERVICE",
			"ALTER ANY DATABASE DDL TRIGGER",
			"ALTER ANY USER",
			"AUTHENTICATE",
			"BACKUP DATABASE",
			"BACKUP LOG",
			"CONTROL",
			"CONNECT",
			"CONNECT REPLICATION",
			"CHECKPOINT",
			"CREATE AGGREGATE",
			"CREATE ASYMMETRIC KEY",
			"CREATE ASSEMBLY",
			"CREATE CERTIFICATE",
			"CREATE DATABASE",
			"CREATE DEFAULT",
			"CREATE DATABASE DDL EVENT NOTIFICATION",
			"CREATE FUNCTION",
			"CREATE FULLTEXT CATALOG",
			"CREATE MESSAGE TYPE",
			"CREATE PROCEDURE",
			"CREATE QUEUE",
			"CREATE ROLE",
			"CREATE ROUTE",
			"CREATE RULE",
			"CREATE REMOTE SERVICE BINDING",
			"CREATE CONTRACT",
			"CREATE SYMMETRIC KEY",
			"CREATE SCHEMA",
			"CREATE SYNONYM",
			"CREATE SERVICE",
			"CREATE TABLE",
			"CREATE TYPE",
			"CREATE VIEW",
			"CREATE XML SCHEMA COLLECTION",
			"DELETE",
			"EXECUTE",
			"IMPERSONATE",
			"INSERT",
			"RECEIVE",
			"REFERENCES",
			"SELECT",
			"SEND",
			"SHOWPLAN",
			"SUBSCRIBE QUERY NOTIFICATIONS",
			"TAKE OWNERSHIP",
			"UPDATE",
			"VIEW DEFINITION",
			"VIEW CHANGE TRACKING",
			"VIEW DATABASE STATE"
		};
	}
}
